repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
  - id: black
    language_version: python3.8
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
  - id: python-no-eval
  - id: python-check-mock-methods
  - id: rst-backticks
  - id: text-unicode-replacement-char
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: bundler-audit
    - id: fasterer
    - id: forbid-binary
    - id: git-check
    - id: reek
    - id: require-ascii
      exclude: '.github'
    - id: script-must-have-extension
    - id: script-must-not-have-extension
    - id: shellcheck
    - id: shfmt
- repo: https://github.com/jorisroovers/gitlint
  rev: 'v0.17.0'
  hooks:
  - id: gitlint
- repo: local
  hooks:
  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: flake8
    types: [python]
- repo: https://github.com/PyCQA/bandit
  rev: '1.7.4'
  hooks:
  - id: bandit
- repo: https://github.com/petalmd/dockerfile-pre-commit
  rev: 'v1.0'
  hooks:
  - id: dockerlint
