---
apiVersion: v1
kind: Namespace
metadata:
  name: operators
  labels:
    kubernetes.io/metadata.name: operators
    name: operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-operator
  namespace: operators
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: console-operator
    namespace: operators
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console-operator
  namespace: operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-operator
  namespace: operators
spec:
  replicas: 1  # do not change to >1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app:  console-operator
  template:
    metadata:
      labels:
        app: console-operator
    spec:
      serviceAccountName: console-operator
      containers:
        - name: operator
          image: kennyopennix/openshift-console-operator
          imagePullPolicy: Always
